# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.srcs/sources_1/ip/clock_wiz_25/clock_wiz_25.xci
# IP: The module: 'clock_wiz_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.srcs/sources_1/ip/clock_wiz_25/clock_wiz_25.xci
# IP: The module: 'clock_wiz_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/patel/Desktop/--/sem7/internship/ankur sir/30_8_2024/30_8_2024.gen/sources_1/ip/clock_wiz_25/clock_wiz_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wiz_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
